name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast:
    name: "SAST - Semgrep"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Semgrep
        run: pip install semgrep

      - name: Ejecutar Semgrep
        run: semgrep --config p/php --config p/security-audit src/ --json --output semgrep-results.json || true

      - name: Mostrar resultados
        run: semgrep --config p/php --config p/security-audit src/
        continue-on-error: true
